# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: portal_administrativo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bportal_administrativo.proto\x12\x07project\"(\n\x05\x41luno\x12\x11\n\tmatricula\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\"(\n\tProfessor\x12\r\n\x05siape\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\"8\n\nDisciplina\x12\r\n\x05sigla\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05vagas\x18\x03 \x01(\x05\"%\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1b\n\rIdentificador\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05Vazia2\x89\x07\n\x14PortalAdministrativo\x12.\n\tNovoAluno\x12\x0e.project.Aluno\x1a\x0f.project.Status\"\x00\x12/\n\nEditaAluno\x12\x0e.project.Aluno\x1a\x0f.project.Status\"\x00\x12\x38\n\x0bRemoveAluno\x12\x16.project.Identificador\x1a\x0f.project.Status\"\x00\x12\x36\n\nObtemAluno\x12\x16.project.Identificador\x1a\x0e.project.Aluno\"\x00\x12\x36\n\x10ObtemTodosAlunos\x12\x0e.project.Vazia\x1a\x0e.project.Aluno\"\x00\x30\x01\x12\x36\n\rNovoProfessor\x12\x12.project.Professor\x1a\x0f.project.Status\"\x00\x12\x37\n\x0e\x45\x64itaProfessor\x12\x12.project.Professor\x1a\x0f.project.Status\"\x00\x12<\n\x0fRemoveProfessor\x12\x16.project.Identificador\x1a\x0f.project.Status\"\x00\x12>\n\x0eObtemProfessor\x12\x16.project.Identificador\x1a\x12.project.Professor\"\x00\x12?\n\x15ObtemTodosProfessores\x12\x0e.project.Vazia\x1a\x12.project.Professor\"\x00\x30\x01\x12\x38\n\x0eNovaDisciplina\x12\x13.project.Disciplina\x1a\x0f.project.Status\"\x00\x12\x39\n\x0f\x45\x64itaDisciplina\x12\x13.project.Disciplina\x1a\x0f.project.Status\"\x00\x12=\n\x10RemoveDisciplina\x12\x16.project.Identificador\x1a\x0f.project.Status\"\x00\x12@\n\x0fObtemDisciplina\x12\x16.project.Identificador\x1a\x13.project.Disciplina\"\x00\x12@\n\x15ObtemTodasDisciplinas\x12\x0e.project.Vazia\x1a\x13.project.Disciplina\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'portal_administrativo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ALUNO']._serialized_start=40
  _globals['_ALUNO']._serialized_end=80
  _globals['_PROFESSOR']._serialized_start=82
  _globals['_PROFESSOR']._serialized_end=122
  _globals['_DISCIPLINA']._serialized_start=124
  _globals['_DISCIPLINA']._serialized_end=180
  _globals['_STATUS']._serialized_start=182
  _globals['_STATUS']._serialized_end=219
  _globals['_IDENTIFICADOR']._serialized_start=221
  _globals['_IDENTIFICADOR']._serialized_end=248
  _globals['_VAZIA']._serialized_start=250
  _globals['_VAZIA']._serialized_end=257
  _globals['_PORTALADMINISTRATIVO']._serialized_start=260
  _globals['_PORTALADMINISTRATIVO']._serialized_end=1165
# @@protoc_insertion_point(module_scope)
