# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: portal_matricula.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.portal_administrativo.protos.portal_administrativo_pb2 as portal__administrativo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16portal_matricula.proto\x12\x07project\x1a\x1bportal_administrativo.proto\"\x85\x01\n\x13RelatorioDisciplina\x12\'\n\ndisciplina\x18\x01 \x01(\x0b\x32\x13.project.Disciplina\x12%\n\tprofessor\x18\x02 \x01(\x0b\x32\x12.project.Professor\x12\x1e\n\x06\x61lunos\x18\x03 \x03(\x0b\x32\x0e.project.Aluno\"w\n\x10ResumoDisciplina\x12\'\n\ndisciplina\x18\x01 \x01(\x0b\x32\x13.project.Disciplina\x12%\n\tprofessor\x18\x02 \x01(\x0b\x32\x12.project.Professor\x12\x13\n\x0btotalAlunos\x18\x03 \x01(\x05\"8\n\x10\x44isciplinaPessoa\x12\x12\n\ndisciplina\x18\x01 \x01(\t\x12\x10\n\x08idPessoa\x18\x02 \x01(\t2\x85\x04\n\x0fPortalMatricula\x12\x41\n\x11\x41\x64icionaProfessor\x12\x19.project.DisciplinaPessoa\x1a\x0f.project.Status\"\x00\x12?\n\x0fRemoveProfessor\x12\x19.project.DisciplinaPessoa\x1a\x0f.project.Status\"\x00\x12=\n\rAdicionaAluno\x12\x19.project.DisciplinaPessoa\x1a\x0f.project.Status\"\x00\x12;\n\x0bRemoveAluno\x12\x19.project.DisciplinaPessoa\x1a\x0f.project.Status\"\x00\x12K\n\x11\x44\x65talhaDisciplina\x12\x16.project.Identificador\x1a\x1c.project.RelatorioDisciplina\"\x00\x12U\n\x19ObtemDisciplinasProfessor\x12\x16.project.Identificador\x1a\x1c.project.RelatorioDisciplina\"\x00\x30\x01\x12N\n\x15ObtemDisciplinasAluno\x12\x16.project.Identificador\x1a\x19.project.ResumoDisciplina\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'portal_matricula_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RELATORIODISCIPLINA']._serialized_start=65
  _globals['_RELATORIODISCIPLINA']._serialized_end=198
  _globals['_RESUMODISCIPLINA']._serialized_start=200
  _globals['_RESUMODISCIPLINA']._serialized_end=319
  _globals['_DISCIPLINAPESSOA']._serialized_start=321
  _globals['_DISCIPLINAPESSOA']._serialized_end=377
  _globals['_PORTALMATRICULA']._serialized_start=380
  _globals['_PORTALMATRICULA']._serialized_end=897
# @@protoc_insertion_point(module_scope)
